// Bakes the current git commit into lib/version.ts at build time. The Deno
// Deploy runtime has no git and no .git directory, so the SHA can't be read at
// runtime — it has to be captured here (locally) before the build is uploaded.
// Runs from the `build` and `start` tasks; the generated file is git-ignored so
// it always reflects HEAD at deploy time instead of a stale committed value.

async function git(args: string[]): Promise<string | null> {
  try {
    const { success, stdout } = await new Deno.Command("git", {
      args,
      stdout: "piped",
      stderr: "null",
    }).output();
    return success ? new TextDecoder().decode(stdout).trim() : null;
  } catch {
    return null;
  }
}

const sha = (await git(["rev-parse", "--short", "HEAD"])) ?? "dev";
const shaFull = (await git(["rev-parse", "HEAD"])) ?? sha;
const builtAt = new Date().toISOString();

const contents =
  `// Generated by scripts/gen-version.ts at build time — do not edit.
export const COMMIT_SHA = ${JSON.stringify(sha)};
export const COMMIT_SHA_FULL = ${JSON.stringify(shaFull)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
`;

await Deno.writeTextFile(
  new URL("../lib/version.ts", import.meta.url),
  contents,
);
console.log(`Wrote lib/version.ts (${sha})`);
