// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/FinalMix.tsx";
import * as $$1 from "./islands/Ingredients.tsx";
import * as $$2 from "./islands/Notes.tsx";
import * as $$3 from "./islands/Poolish.tsx";
import * as $$4 from "./islands/PoolishHeading.tsx";
import * as $$5 from "./islands/Slider.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/FinalMix.tsx": $$0,
    "./islands/Ingredients.tsx": $$1,
    "./islands/Notes.tsx": $$2,
    "./islands/Poolish.tsx": $$3,
    "./islands/PoolishHeading.tsx": $$4,
    "./islands/Slider.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
